apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: buildah-ass
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: https://github.com/upslopeio/lint-markdown-files
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: markdown-lint
      taskRef:
        name: markdown-lint
      runAfter:
        - git-clone
      workspaces:
        - name: shared-workspace
          workspace: pipeline-shared-data
      params:
        - name: args
          value: ["."]
  workspaces:
    - name: pipeline-shared-data