apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: quay.io/upslopeio/express-sample-app
  newName: quay.io/timothy_credo/buildah_pipeline_assignment
  newTag: 91c54d96b90a97f509fa5bd501daa54a4f322e93
