apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: push-image-buildah
spec:
  params:
    - name: source-repo
      type: string
    - name: image-repo
      type: string
      description: Docker image repository
  tasks:
    - name: git-clone
      params:
        - name: url
          value: "$(params.source-repo)"
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: create-image
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      runAfter:
        - git-clone
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: pipeline-shared-data
  workspaces:
    - name: pipeline-shared-data